# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fun_analysis',
                'doc_host': 'https://italocegatta.github.io',
                'git_url': 'https://github.com/italocegatta/fun_analysis',
                'lib_path': 'fun_analysis'},
  'syms': {'fun_analysis.core': {'fun_analysis.core.foo': ('core.html#foo', 'fun_analysis/core.py')}}}
